"""
AES-256-GCM implemented from scratch.

This file is a direct port of Backend/utils/scratch/aes256gcm.js — same
S-box, same RCON, same 14-round structure, same 12-byte-IV restriction,
same GHASH polynomial.

The big picture
─────────────────────────────────────────────────────────────────────────────
This file does two distinct things stacked on top of each other:

  1. AES-256 (FIPS PUB 197) — a *block cipher*. Given a 32-byte key and a
     16-byte input block, it produces a 16-byte output block, deterministic
     and reversible. AES on its own only knows how to mangle one block at
     a time. It cannot encrypt a 17-byte file, it cannot detect tampering,
     and it cannot use the same key safely on two different messages.

  2. GCM (NIST SP 800-38D) — a *mode of operation* that wraps a block
     cipher to give you (a) confidentiality of arbitrary-length data and
     (b) authenticity (a tag that detects any tampering, including changes
     to "associated data" that is sent alongside but not encrypted).

Why GCM instead of "encrypt-then-MAC"
─────────────────────────────────────────────────────────────────────────────
The traditional way to get authenticated encryption is to encrypt with one
key and MAC with another (e.g., AES-CBC + HMAC-SHA256). GCM bundles both
jobs into a single pass over the data using only AES — no separate hash
function and no second key. It is faster on modern CPUs and has a clean
security proof.

GCM is built from two ingredients:
  - CTR mode for confidentiality. We turn AES into a stream cipher by
    encrypting an incrementing counter and XORing the result with the
    plaintext. Decryption is the same operation (XOR is self-inverse), so
    we never call AES decryption.
  - GHASH for authenticity. We compute a polynomial hash over the AAD,
    the ciphertext, and the lengths, in a finite field of 2^128 elements.
    The hash is "keyed" by H = AES(zero block), and its output is XORed
    with one more AES output to produce the final 16-byte authentication
    tag.

IV length policy
─────────────────────────────────────────────────────────────────────────────
The GCM spec allows arbitrary IV lengths via a GHASH-derived J0. In
practice every real-world GCM deployment uses a 12-byte IV, because the
12-byte branch has a simple closed form: J0 = IV || 0x00000001. We hard
reject any other length to keep the code simple and to discourage caller
mistakes.

The GCM bit-reversal gotcha
─────────────────────────────────────────────────────────────────────────────
GCM's GF(2^128) numbers the bits of a 16-byte buffer "backwards". The
leftmost (high-order) bit of byte 0 is treated as the lowest-degree
coefficient (x^0), and the rightmost (low-order) bit of byte 15 is the
highest-degree coefficient (x^127). This is the opposite of how every
other "treat a buffer as a big number" convention works.

The practical consequence: "multiply by x" in GF(2^128) — which
mathematically shifts coefficients up by one degree — looks like a
*right* shift of the byte buffer, with reduction by the magic value 0xE1
(the bit-reversal of 0x87, the natural form of the AES polynomial). If
you write GHASH using the "obvious" left-shift convention you get a
function that produces the wrong answer on every input. This is the
single most common GCM implementation bug.

Allowed dependencies
─────────────────────────────────────────────────────────────────────────────
Zero. AES-GCM is self-contained — no imports for the algorithm itself.
The optional cross-check at the bottom imports `cryptography` purely as a
reference; clearly marked.
"""


# ─────────────────────────────────────────────────────────────────────────────
# Custom exception — clearer than ValueError when callers catch
# ─────────────────────────────────────────────────────────────────────────────

class GCMAuthenticationError(Exception):
    """Raised by aes256_gcm_decrypt when the authentication tag does not
    match the recomputed expected tag. Always thrown BEFORE any plaintext
    is returned, so the caller cannot use this routine as a decryption
    oracle on tampered input."""
    pass


# ═════════════════════════════════════════════════════════════════════════════
#  PART A — AES-256 block cipher (FIPS PUB 197)
# ═════════════════════════════════════════════════════════════════════════════


# ─────────────────────────────────────────────────────────────────────────────
# Constants — S-box and round constants
# ─────────────────────────────────────────────────────────────────────────────

# _S_BOX — the AES forward substitution box.
#
# Each byte value 0..255 maps to a fixed permuted byte. The mathematical
# derivation is: S_BOX[b] = affine_transform( multiplicative_inverse_in_GF(2^8)(b) ),
# where the inverse is taken in the field GF(2^8) generated by the irreducible
# polynomial x^8 + x^4 + x^3 + x + 1 (= 0x11B), and the affine transform is a
# fixed bit matrix multiply plus XOR with 0x63.
#
# We could compute this at runtime, but for clarity we inline the standard
# 256-entry table verbatim from the FIPS 197 specification. Treat it as a
# lookup table; every AES implementation in the world uses these exact bytes.
_S_BOX = bytes((
    0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
    0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
    0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
    0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
    0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
    0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
    0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
    0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
    0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
    0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
    0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
    0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
    0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
    0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
    0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
    0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16,
))

# _RCON — round constants used by the AES-256 key schedule.
#
# Each value is the high byte of a 4-byte word; the other three bytes are 0.
# The values are powers of x in GF(2^8): RCON[i] = x^(i+1) reduced by the
# AES polynomial. AES-256 needs only 7 entries because the key schedule
# applies a round constant once every 8 words, and there are 60 words in
# the expanded key (60 = 8 + 7*8 + 4 leftover).
_RCON = (0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40)


# ─────────────────────────────────────────────────────────────────────────────
# AES helpers
# ─────────────────────────────────────────────────────────────────────────────

def _gmul(a, b):
    """Multiply two bytes in GF(2^8) using the AES irreducible polynomial 0x11B.

    This is the "Russian peasant" or shift-and-XOR algorithm: walk the bits
    of `b` from low to high; whenever a bit is set, XOR the running value of
    `a` into the product; then double `a` (shift left by 1), reducing modulo
    0x11B whenever the shift would overflow 8 bits.

    Used only by _mix_columns. Constants 2 and 3 cover all the multiplications
    needed by encryption.
    """
    p = 0
    for _ in range(8):
        if b & 1:
            p ^= a
        hi = a & 0x80                     # is the high bit set before doubling?
        a = (a << 1) & 0xff               # double in GF(2^8) — i.e. shift left
        if hi:
            a ^= 0x1b                     # reduction: x^8 = x^4+x^3+x+1 → 0x1B
        b >>= 1
    return p


def _sub_bytes(state):
    """SubBytes — substitute each of the 16 state bytes through the S-box.

    Operates on the 16-byte bytearray in place. This is the only non-linear
    step in AES; without it AES would degenerate to a system of linear
    equations over GF(2) and be trivially breakable.
    """
    for i in range(16):
        state[i] = _S_BOX[state[i]]


def _shift_rows(state):
    """ShiftRows — cyclically shift the rows of the 4x4 state matrix.

    The state is stored column-major in a 16-byte buffer:

         column 0   column 1   column 2   column 3
      r0 state[0]   state[4]   state[8]   state[12]
      r1 state[1]   state[5]   state[9]   state[13]
      r2 state[2]   state[6]   state[10]  state[14]
      r3 state[3]   state[7]   state[11]  state[15]

    Row 0 stays put; row 1 rotates left by 1; row 2 by 2; row 3 by 3.
    Together with MixColumns this provides the diffusion property — small
    changes in one byte propagate to many bytes after a few rounds.
    """
    # Row 1: left rotate by 1  →  [a,b,c,d] becomes [b,c,d,a]
    t1 = state[1]
    state[1]  = state[5]
    state[5]  = state[9]
    state[9]  = state[13]
    state[13] = t1

    # Row 2: left rotate by 2  →  [a,b,c,d] becomes [c,d,a,b]  (= two swaps)
    state[2],  state[10] = state[10], state[2]
    state[6],  state[14] = state[14], state[6]

    # Row 3: left rotate by 3 (= right rotate by 1)
    t3 = state[15]
    state[15] = state[11]
    state[11] = state[7]
    state[7]  = state[3]
    state[3]  = t3


def _mix_columns(state):
    """MixColumns — multiply each column of the state by a fixed matrix in GF(2^8).

    For each column [s0, s1, s2, s3] the new column is:

         [ 2 3 1 1 ] [ s0 ]
         [ 1 2 3 1 ] [ s1 ]
         [ 1 1 2 3 ] [ s2 ]
         [ 3 1 1 2 ] [ s3 ]

    The matrix coefficients are GF(2^8) field elements — multiplication is
    done by `_gmul`. This operation mixes information *across* rows; ShiftRows
    mixes across columns. Together they spread one input byte's influence
    to all 16 output bytes after just two rounds.
    """
    for c in range(4):
        s0 = state[4 * c + 0]
        s1 = state[4 * c + 1]
        s2 = state[4 * c + 2]
        s3 = state[4 * c + 3]

        state[4 * c + 0] = _gmul(2, s0) ^ _gmul(3, s1) ^ s2          ^ s3
        state[4 * c + 1] = s0           ^ _gmul(2, s1) ^ _gmul(3, s2) ^ s3
        state[4 * c + 2] = s0           ^ s1           ^ _gmul(2, s2) ^ _gmul(3, s3)
        state[4 * c + 3] = _gmul(3, s0) ^ s1           ^ s2           ^ _gmul(2, s3)


def _add_round_key(state, expanded_key, round_idx):
    """AddRoundKey — XOR the state with 16 bytes of the expanded key.

    The `round_idx` argument selects which 16-byte slice of the expanded
    key to use: round 0 uses bytes 0..15, round 1 uses 16..31, ..., round
    14 uses bytes 224..239. AES-256 has 14 rounds and 15 round keys.

    AddRoundKey is the *only* place where the key affects the state. Every
    other step is keyless and the same for every user — the entire security
    comes from the round keys.
    """
    offset = round_idx * 16
    for i in range(16):
        state[i] ^= expanded_key[offset + i]


def _key_expansion(key):
    """Expand a 32-byte key into a 240-byte round-key schedule.

    AES-256 derives 60 4-byte words (= 240 bytes = 15 round keys of 16 bytes)
    from the 32-byte (= 8 word) input key. The first 8 words are the key
    itself; each subsequent word `w[i]` is computed from `w[i-1]` and
    `w[i-8]`, with two special cases:

      - Every 8th word (i.e. i % 8 == 0): apply RotWord (cyclic byte
        rotation), then SubWord (S-box on each byte), then XOR the high
        byte with the next round constant.
      - Every (8k+4)th word (i % 8 == 4): SubWord only, no RotWord and
        no RCON.

    The "% 8 == 4" branch is unique to AES-256; AES-128 does not have it.
    """
    if len(key) != 32:
        raise ValueError(f"_key_expansion: key must be 32 bytes (got {len(key)})")

    N = 8       # input key length in 32-bit words
    TOTAL = 60  # total words in the expanded key (15 round keys * 4 words)

    # Pack the 32 input bytes into eight big-endian 32-bit words.
    w = [0] * TOTAL
    for i in range(N):
        w[i] = (
            (key[4 * i]     << 24) |
            (key[4 * i + 1] << 16) |
            (key[4 * i + 2] <<  8) |
             key[4 * i + 3]
        ) & 0xFFFFFFFF

    for i in range(N, TOTAL):
        temp = w[i - 1]

        if i % N == 0:
            # RotWord: rotate left by one byte.
            temp = ((temp << 8) | (temp >> 24)) & 0xFFFFFFFF
            # SubWord: apply S-box to each byte.
            temp = (
                (_S_BOX[(temp >> 24) & 0xff] << 24) |
                (_S_BOX[(temp >> 16) & 0xff] << 16) |
                (_S_BOX[(temp >>  8) & 0xff] <<  8) |
                 _S_BOX[ temp        & 0xff]
            ) & 0xFFFFFFFF
            # XOR the round constant into the high byte.
            # _RCON is 0-indexed; the round-key index uses (i // N - 1).
            temp = (temp ^ (_RCON[(i // N) - 1] << 24)) & 0xFFFFFFFF
        elif i % N == 4:
            # SubWord only — AES-256-specific extra mixing step.
            temp = (
                (_S_BOX[(temp >> 24) & 0xff] << 24) |
                (_S_BOX[(temp >> 16) & 0xff] << 16) |
                (_S_BOX[(temp >>  8) & 0xff] <<  8) |
                 _S_BOX[ temp        & 0xff]
            ) & 0xFFFFFFFF

        w[i] = (w[i - N] ^ temp) & 0xFFFFFFFF

    # Serialize the 60 words back into a 240-byte buffer (big-endian).
    expanded = bytearray(240)
    for i in range(TOTAL):
        expanded[4 * i + 0] = (w[i] >> 24) & 0xff
        expanded[4 * i + 1] = (w[i] >> 16) & 0xff
        expanded[4 * i + 2] = (w[i] >>  8) & 0xff
        expanded[4 * i + 3] =  w[i]        & 0xff
    return bytes(expanded)


def _aes_encrypt_block(block, expanded_key):
    """Encrypt one 16-byte block under an expanded AES-256 key.

    The structure is:
      - AddRoundKey with round-key 0 (the only thing applied before the
        rounds proper)
      - 13 main rounds: SubBytes → ShiftRows → MixColumns → AddRoundKey(t)
      - 1 final round: SubBytes → ShiftRows → AddRoundKey(14)
        (the final round drops MixColumns, by design — it would not improve
        diffusion since the next AddRoundKey absorbs anything it could do)

    Returns a fresh 16-byte bytes; does not mutate the input.
    """
    if len(block) != 16:
        raise ValueError(f"_aes_encrypt_block: block must be 16 bytes (got {len(block)})")

    state = bytearray(block)            # working copy

    _add_round_key(state, expanded_key, 0)

    for round_idx in range(1, 14):
        _sub_bytes(state)
        _shift_rows(state)
        _mix_columns(state)
        _add_round_key(state, expanded_key, round_idx)

    # Final round — note the absence of MixColumns.
    _sub_bytes(state)
    _shift_rows(state)
    _add_round_key(state, expanded_key, 14)

    return bytes(state)


# ═════════════════════════════════════════════════════════════════════════════
#  PART B — GCM mode (NIST SP 800-38D)
# ═════════════════════════════════════════════════════════════════════════════


def _ghash_multiply(x, y):
    """Multiply two 16-byte buffers as elements of GF(2^128) using GCM's
    polynomial x^128 + x^7 + x^2 + x + 1 and GCM's bit ordering.

    Recall the bit-reversal convention: the leftmost bit of byte 0 of X
    is the coefficient of x^0; the rightmost bit of byte 15 of X is the
    coefficient of x^127.

    Algorithm: walk the bits of X from x^0 to x^127. Maintain a "shifted Y"
    accumulator V that starts equal to Y and is multiplied by x after every
    iteration. Whenever the current X bit is set, XOR V into the result Z.

    "Multiply V by x" is implemented as a *right* shift of the 128-bit
    buffer (because of the bit-reversal convention), with the bit shifted
    out of the LSB end triggering an XOR with 0xE1 in byte 0 to perform
    the polynomial reduction.
    """
    z = bytearray(16)                   # accumulator, starts at zero
    v = bytearray(y)                    # running "Y * x^i", starts at Y

    for i in range(128):
        # Read bit i of X under GCM's convention:
        #   i=0 → byte 0, bit 7 (MSB)
        #   i=7 → byte 0, bit 0 (LSB)
        #   i=8 → byte 1, bit 7
        #   ...
        x_byte = i >> 3
        x_bit  = 7 - (i & 7)
        if (x[x_byte] >> x_bit) & 1:
            # Z ^= V
            for k in range(16):
                z[k] ^= v[k]

        # V *= x  (right-shift the buffer by 1 bit, with reduction)
        lsb = v[15] & 1                 # coefficient of x^127 before shift
        for k in range(15, 0, -1):
            v[k] = ((v[k] >> 1) | ((v[k - 1] & 1) << 7)) & 0xff
        v[0] = (v[0] >> 1) & 0xff
        if lsb:
            # Reduction: bit fell off the high end → add x^128 mod P
            # = x^7 + x^2 + x + 1, which lives in byte 0 as 0xE1 in
            # GCM's bit-reversed encoding.
            v[0] ^= 0xe1

    return bytes(z)


def _ghash(h, data):
    """Hash a sequence of 16-byte blocks under key H.

    Y starts at zero. For each block, XOR it into Y, then multiply Y by H.
    The final Y is the hash.

    `data` MUST already be a multiple of 16 bytes — pad it with zeros
    before calling. We do this in the encrypt/decrypt routines via
    _pad_to_block.
    """
    if len(data) % 16 != 0:
        raise ValueError(f"_ghash: data length must be a multiple of 16 (got {len(data)})")

    y = bytearray(16)                   # accumulator starts at zero

    for offset in range(0, len(data), 16):
        # Y ^= block
        for k in range(16):
            y[k] ^= data[offset + k]
        # Y = Y * H  (in GF(2^128))
        y = bytearray(_ghash_multiply(h, y))

    return bytes(y)


def _pad_to_block(buf):
    """Return a copy of `buf` zero-padded to the next 16-byte boundary.

    GCM's GHASH input format is "AAD padded || ciphertext padded || lengths".
    Both the AAD and ciphertext sections must be a whole number of 16-byte
    blocks; if either has a partial last block, the spec says to right-pad
    with zeros up to the boundary.
    """
    remainder = len(buf) % 16
    if remainder == 0:
        return bytes(buf)
    return bytes(buf) + b'\x00' * (16 - remainder)


def _increment_counter(counter):
    """Increment the last 4 bytes of a 16-byte counter as a big-endian
    32-bit integer. The first 12 bytes (the IV portion) stay fixed.

    GCM uses this between successive blocks of the keystream: each block
    of keystream is AES(counter), and the counter advances by 1 for the
    next block. With a 32-bit counter we can encrypt up to 2^32 - 2 blocks
    under one (key, IV) pair — about 64 GiB of data.
    """
    high = counter[:12]
    low_int = int.from_bytes(counter[12:], 'big')
    low_int = (low_int + 1) & 0xFFFFFFFF
    return bytes(high) + low_int.to_bytes(4, 'big')


def _gctr(expanded_key, initial_counter, input_buf):
    """GCM counter mode encryption.

    Walk the input in 16-byte chunks. For each chunk:
      - encrypt the current counter to produce a 16-byte keystream block
      - XOR the keystream with the input chunk
      - increment the counter

    The last chunk may be shorter than 16 bytes; we use only as many
    keystream bytes as we need. Decryption is the same operation
    (XOR is self-inverse).
    """
    output  = bytearray(len(input_buf))
    counter = initial_counter

    offset = 0
    while offset < len(input_buf):
        keystream = _aes_encrypt_block(counter, expanded_key)
        block_len = min(16, len(input_buf) - offset)
        for i in range(block_len):
            output[offset + i] = input_buf[offset + i] ^ keystream[i]
        counter = _increment_counter(counter)
        offset += block_len

    return bytes(output)


def _constant_time_equal(a, b):
    """XOR-and-OR comparison that does not short-circuit.

    For tag verification we cannot use plain `==`: that returns as soon
    as it sees the first different byte, which leaks information about
    *where* the tag mismatched via timing. Walking every byte with
    bitwise OR makes the comparison time depend only on length, not on
    contents.
    """
    if len(a) != len(b):
        return False
    diff = 0
    for x, y in zip(a, b):
        diff |= x ^ y
    return diff == 0


# ─────────────────────────────────────────────────────────────────────────────
# Top-level entry points
# ─────────────────────────────────────────────────────────────────────────────

def _to_bytes(value, label):
    """Coerce a string-or-bytes input to bytes (UTF-8 encoded for strings).

    Used for plaintext, ciphertext (where allowed), and aad. `None` is
    treated as empty input — handy for the optional `aad` argument.
    """
    if value is None:
        return b''
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    if isinstance(value, str):
        return value.encode('utf-8')
    raise TypeError(f"aes256_gcm: {label} must be str, bytes, bytearray, or None")


def aes256_gcm_encrypt(key, iv, plaintext, aad=b''):
    """Encrypt and authenticate `plaintext` under (`key`, `iv`), with optional
    additional authenticated data `aad`.

    Args:
        key:       32 bytes (bytes or bytearray)
        iv:        exactly 12 bytes (other lengths rejected)
        plaintext: any length, including 0; bytes, bytearray, or str
        aad:       any length, including 0; bytes, bytearray, str, or None

    Returns:
        (ciphertext, tag) — ciphertext is same length as plaintext;
        tag is exactly 16 bytes.
    """
    if not isinstance(key, (bytes, bytearray)) or len(key) != 32:
        raise ValueError("aes256_gcm_encrypt: key must be 32 bytes (bytes or bytearray)")
    if not isinstance(iv, (bytes, bytearray)) or len(iv) != 12:
        raise ValueError(
            "aes256_gcm_encrypt: iv must be exactly 12 bytes (we restrict to "
            "the standard 12-byte IV path; other lengths are rejected)"
        )

    pt_buf  = _to_bytes(plaintext, 'plaintext')
    aad_buf = _to_bytes(aad,       'aad')

    expanded_key = _key_expansion(bytes(key))

    # Step 1: H = AES_K(0^128). H is the GHASH key.
    h = _aes_encrypt_block(bytes(16), expanded_key)

    # Step 2: J0 = IV || 0x00000001    (12-byte IV path only)
    j0 = bytes(iv) + b'\x00\x00\x00\x01'

    # Step 3: encrypt with CTR starting at J0 + 1
    initial_ctr = _increment_counter(j0)
    ciphertext  = _gctr(expanded_key, initial_ctr, pt_buf)

    # Step 4: assemble the GHASH input
    #   AAD padded to next 16-byte boundary
    #   || ciphertext padded to next 16-byte boundary
    #   || (len(AAD) in bits as 64-bit BE) (len(CT) in bits as 64-bit BE)
    lengths_block = (
        (len(aad_buf)    * 8).to_bytes(8, 'big') +
        (len(ciphertext) * 8).to_bytes(8, 'big')
    )
    ghash_input = _pad_to_block(aad_buf) + _pad_to_block(ciphertext) + lengths_block
    s = _ghash(h, ghash_input)

    # Step 5: tag = S XOR AES_K(J0)
    j0_encrypted = _aes_encrypt_block(j0, expanded_key)
    tag = bytes(a ^ b for a, b in zip(s, j0_encrypted))

    return ciphertext, tag


def aes256_gcm_decrypt(key, iv, ciphertext, tag, aad=b''):
    """Verify the authentication tag and (only on success) decrypt
    `ciphertext` under (`key`, `iv`) with the same `aad` used at encrypt
    time.

    Raises GCMAuthenticationError on any tag mismatch BEFORE any
    plaintext is returned, so a caller cannot use this routine as a
    decryption oracle.
    """
    if not isinstance(key, (bytes, bytearray)) or len(key) != 32:
        raise ValueError("aes256_gcm_decrypt: key must be 32 bytes (bytes or bytearray)")
    if not isinstance(iv, (bytes, bytearray)) or len(iv) != 12:
        raise ValueError("aes256_gcm_decrypt: iv must be exactly 12 bytes")
    if not isinstance(tag, (bytes, bytearray)) or len(tag) != 16:
        raise ValueError("aes256_gcm_decrypt: tag must be exactly 16 bytes")

    if not isinstance(ciphertext, (bytes, bytearray)):
        raise TypeError("aes256_gcm_decrypt: ciphertext must be bytes or bytearray")
    ct_buf  = bytes(ciphertext)
    aad_buf = _to_bytes(aad, 'aad')

    expanded_key = _key_expansion(bytes(key))

    # Reproduce H, J0, and the expected tag exactly as the encrypt side did.
    h  = _aes_encrypt_block(bytes(16), expanded_key)
    j0 = bytes(iv) + b'\x00\x00\x00\x01'

    lengths_block = (
        (len(aad_buf) * 8).to_bytes(8, 'big') +
        (len(ct_buf)  * 8).to_bytes(8, 'big')
    )
    ghash_input = _pad_to_block(aad_buf) + _pad_to_block(ct_buf) + lengths_block
    s = _ghash(h, ghash_input)

    j0_encrypted = _aes_encrypt_block(j0, expanded_key)
    expected_tag = bytes(a ^ b for a, b in zip(s, j0_encrypted))

    # Verify BEFORE producing plaintext — never expose the keystream to a
    # caller who supplied a bad tag.
    if not _constant_time_equal(expected_tag, bytes(tag)):
        raise GCMAuthenticationError("GCM authentication failed")

    # Tag is good — decrypt by running CTR mode again (same operation as encrypt).
    initial_ctr = _increment_counter(j0)
    return _gctr(expanded_key, initial_ctr, ct_buf)


# ─────────────────────────────────────────────────────────────────────────────
# Self-test — runs only when this file is executed directly:
#   python aes256gcm.py
# Three NIST SP 800-38D Appendix B test vectors. Each checks both the
# ciphertext and the authentication tag. All three should print PASS.
# Then a 20-iteration random round-trip and a tampered-tag rejection test.
# Optional cross-check vs `cryptography` if it is installed.
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    import os

    vectors = [
        {
            'name':         'Test 1 (empty PT, empty AAD)',
            'key':          bytes(32),
            'iv':           bytes(12),
            'plaintext':    b'',
            'aad':          b'',
            'expected_ct':  b'',
            'expected_tag': bytes.fromhex('530f8afbc74536b9a963b4f1c4cb738b'),
        },
        {
            'name':         'Test 2 (16-byte zero PT, empty AAD)',
            'key':          bytes(32),
            'iv':           bytes(12),
            'plaintext':    bytes(16),
            'aad':          b'',
            'expected_ct':  bytes.fromhex('cea7403d4d606b6e074ec5d3baf39d18'),
            'expected_tag': bytes.fromhex('d0d1c8a799996bf0265b98b5d48ab919'),
        },
        {
            'name':         'Test 3 (60-byte PT + 20-byte AAD)',
            'key':          bytes.fromhex(
                'feffe9928665731c6d6a8f9467308308feffe9928665731c6d6a8f9467308308'
            ),
            'iv':           bytes.fromhex('cafebabefacedbaddecaf888'),
            'plaintext':    bytes.fromhex(
                'd9313225f88406e5a55909c5aff5269a86a7a9531534f7da2e4c303d8a318a72'
                '1c3c0c95956809532fcf0e2449a6b525b16aedf5aa0de657ba637b39'
            ),
            'aad':          bytes.fromhex('feedfacedeadbeeffeedfacedeadbeefabaddad2'),
            'expected_ct':  bytes.fromhex(
                '522dc1f099567d07f47f37a32a84427d643a8cdcbfe5c0c97598a2bd2555d1aa'
                '8cb08e48590dbb3da7b08b1056828838c5f61e6393ba7a0abcc9f662'
            ),
            'expected_tag': bytes.fromhex('76fc6ece0f4e1768cddf8853bb2d551b'),
        },
    ]

    all_pass = True
    for v in vectors:
        ct, tag = aes256_gcm_encrypt(v['key'], v['iv'], v['plaintext'], v['aad'])
        ct_ok  = ct  == v['expected_ct']
        tag_ok = tag == v['expected_tag']
        if ct_ok and tag_ok:
            print(f"PASS  {v['name']} (NIST SP 800-38D)")
        else:
            all_pass = False
            print(f"FAIL  {v['name']}")
            if not ct_ok:
                print(f"      ct expected: {v['expected_ct'].hex()}")
                print(f"      ct got:      {ct.hex()}")
            if not tag_ok:
                print(f"      tag expected: {v['expected_tag'].hex()}")
                print(f"      tag got:      {tag.hex()}")

    if not all_pass:
        sys.exit(1)

    # ── Test 4: round-trip with random data (scratch self-consistency) ──
    n_iter = 20
    rt_pass = 0
    for i in range(n_iter):
        rkey  = os.urandom(32)
        riv   = os.urandom(12)
        pt    = os.urandom(int.from_bytes(os.urandom(2), 'big') % 501)   # [0, 500]
        rad   = os.urandom(int.from_bytes(os.urandom(2), 'big') % 101)   # [0, 100]

        ct, tag = aes256_gcm_encrypt(rkey, riv, pt, rad)
        recovered = aes256_gcm_decrypt(rkey, riv, ct, tag, rad)
        if recovered == pt:
            rt_pass += 1
        else:
            print(f"FAIL  round-trip iteration {i + 1}")
            print(f"      pt_len={len(pt)} aad_len={len(rad)}")
            print(f"      key (hex):   {rkey.hex()}")
            print(f"      iv (hex):    {riv.hex()}")
            print(f"      pt (hex):    {pt.hex()}")
            print(f"      recovered:   {recovered.hex()}")
            sys.exit(1)
    print(f"round-trip {rt_pass}/{n_iter} PASS")

    # ── Test 5: tampered tag rejection ──────────────────────────────────
    rkey = bytes(32)
    riv  = bytes(12)
    ct, tag = aes256_gcm_encrypt(rkey, riv, b'plaintext for tamper test', b'')
    bad_tag = bytearray(tag)
    bad_tag[0] ^= 0x01
    try:
        aes256_gcm_decrypt(rkey, riv, ct, bytes(bad_tag), b'')
        print("FAIL  tampered-tag NOT rejected — security failure")
        sys.exit(1)
    except GCMAuthenticationError:
        print("tampered-tag rejection: PASS")

    # cross-check vs cryptography (not the source of truth)
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        n_cross = 20
        cross_pass = 0
        for i in range(n_cross):
            ckey = os.urandom(32)
            civ  = os.urandom(12)
            pt   = os.urandom(int.from_bytes(os.urandom(2), 'big') % 501)
            cad  = os.urandom(int.from_bytes(os.urandom(2), 'big') % 101)

            # Direction A: scratch encrypt → cryptography decrypt
            sct, stag = aes256_gcm_encrypt(ckey, civ, pt, cad)
            ref = AESGCM(ckey).decrypt(civ, sct + stag, cad)
            if ref != pt:
                print(f"FAIL  cross-check A iteration {i + 1}")
                sys.exit(1)

            # Direction B: cryptography encrypt → scratch decrypt
            lib_combined = AESGCM(ckey).encrypt(civ, pt, cad)
            lib_ct, lib_tag = lib_combined[:-16], lib_combined[-16:]
            recovered = aes256_gcm_decrypt(ckey, civ, lib_ct, lib_tag, cad)
            if recovered != pt:
                print(f"FAIL  cross-check B iteration {i + 1}")
                sys.exit(1)
            cross_pass += 1

        print(f"cross-check vs cryptography: {cross_pass}/{n_cross} PASS")
    except ImportError:
        print("cross-check skipped (cryptography not installed)")
