'use strict';

/*
 * AES-256-GCM implemented from scratch.
 *
 * The big picture
 * ─────────────────────────────────────────────────────────────────────────────
 * This file does two distinct things stacked on top of each other:
 *
 *   1. AES-256 (FIPS PUB 197) — a *block cipher*. Given a 32-byte key and a
 *      16-byte input block, it produces a 16-byte output block, deterministic
 *      and reversible. AES on its own only knows how to mangle one block at
 *      a time. It cannot encrypt a 17-byte file, it cannot detect tampering,
 *      and it cannot use the same key safely on two different messages.
 *
 *   2. GCM (NIST SP 800-38D) — a *mode of operation* that wraps a block
 *      cipher to give you (a) confidentiality of arbitrary-length data and
 *      (b) authenticity (a tag that detects any tampering, including changes
 *      to "associated data" that is sent alongside but not encrypted).
 *
 * Why GCM instead of "encrypt-then-MAC"
 * ─────────────────────────────────────────────────────────────────────────────
 * The traditional way to get authenticated encryption is to encrypt with one
 * key and MAC with another (e.g., AES-CBC + HMAC-SHA256). GCM bundles both
 * jobs into a single pass over the data using only AES — no separate hash
 * function and no second key. It is faster on modern CPUs and has a clean
 * security proof.
 *
 * GCM is built from two ingredients:
 *   - CTR mode for confidentiality. We turn AES into a stream cipher by
 *     encrypting an incrementing counter and XORing the result with the
 *     plaintext. Decryption is the same operation (XOR is self-inverse), so
 *     we never call AES decryption.
 *   - GHASH for authenticity. We compute a polynomial hash over the AAD,
 *     the ciphertext, and the lengths, in a finite field of 2^128 elements.
 *     The hash is "keyed" by H = AES(zero block), and its output is XORed
 *     with one more AES output to produce the final 16-byte authentication
 *     tag.
 *
 * IV length policy
 * ─────────────────────────────────────────────────────────────────────────────
 * The GCM spec allows arbitrary IV lengths via a GHASH-derived J0. In
 * practice every real-world GCM deployment uses a 12-byte IV, because the
 * 12-byte branch has a simple closed form: J0 = IV || 0x00000001. We hard
 * reject any other length to keep the code simple and to discourage
 * caller mistakes.
 *
 * The GCM bit-reversal gotcha
 * ─────────────────────────────────────────────────────────────────────────────
 * GCM's GF(2^128) numbers the bits of a 16-byte buffer "backwards". The
 * leftmost (high-order) bit of byte 0 is treated as the lowest-degree
 * coefficient (x^0), and the rightmost (low-order) bit of byte 15 is the
 * highest-degree coefficient (x^127). This is the opposite of how every
 * other "treat a buffer as a big number" convention works.
 *
 * The practical consequence: "multiply by x" in GF(2^128) — which
 * mathematically shifts coefficients up by one degree — looks like a
 * *right* shift of the byte buffer, with reduction by the magic value 0xE1
 * (which is just the bit-reversal of 0x87, the natural form of the AES
 * polynomial). If you write GHASH using the "obvious" left-shift convention
 * you get a function that produces the wrong answer on every input. This
 * is the most common GCM bug.
 *
 * Allowed dependencies
 * ─────────────────────────────────────────────────────────────────────────────
 * Zero. AES-GCM is self-contained — no require() in this file.
 */


// ═════════════════════════════════════════════════════════════════════════════
//  PART A — AES-256 block cipher (FIPS PUB 197)
// ═════════════════════════════════════════════════════════════════════════════


// ─────────────────────────────────────────────────────────────────────────────
// Constants — S-box, inverse S-box, round constants
// ─────────────────────────────────────────────────────────────────────────────

/*
 * S_BOX — the AES forward substitution box.
 *
 * Each byte value 0..255 maps to a fixed permuted byte. The mathematical
 * derivation is: S_BOX[b] = affine_transform( multiplicative_inverse_in_GF(2^8)(b) ),
 * where the inverse is taken in the field GF(2^8) generated by the irreducible
 * polynomial x^8 + x^4 + x^3 + x + 1 (= 0x11B), and the affine transform is a
 * fixed bit matrix multiply plus XOR with 0x63.
 *
 * We could compute this at runtime, but for clarity we inline the standard
 * 256-entry table verbatim from the FIPS 197 specification. Treat it as a
 * lookup table; every AES implementation in the world uses these exact bytes.
 */
const S_BOX = new Uint8Array([
    0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
    0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
    0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
    0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
    0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
    0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
    0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
    0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
    0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
    0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
    0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
    0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
    0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
    0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
    0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
    0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16
]);

/*
 * INV_S_BOX — the inverse of S_BOX (S_BOX[INV_S_BOX[b]] === b for every b).
 *
 * GCM does NOT actually use this table — it never calls AES decryption,
 * because CTR mode uses the forward AES even on the decrypt side. We define
 * it here for completeness so the file documents both halves of FIPS 197.
 */
const INV_S_BOX = new Uint8Array([
    0x52, 0x09, 0x6a, 0xd5, 0x30, 0x36, 0xa5, 0x38, 0xbf, 0x40, 0xa3, 0x9e, 0x81, 0xf3, 0xd7, 0xfb,
    0x7c, 0xe3, 0x39, 0x82, 0x9b, 0x2f, 0xff, 0x87, 0x34, 0x8e, 0x43, 0x44, 0xc4, 0xde, 0xe9, 0xcb,
    0x54, 0x7b, 0x94, 0x32, 0xa6, 0xc2, 0x23, 0x3d, 0xee, 0x4c, 0x95, 0x0b, 0x42, 0xfa, 0xc3, 0x4e,
    0x08, 0x2e, 0xa1, 0x66, 0x28, 0xd9, 0x24, 0xb2, 0x76, 0x5b, 0xa2, 0x49, 0x6d, 0x8b, 0xd1, 0x25,
    0x72, 0xf8, 0xf6, 0x64, 0x86, 0x68, 0x98, 0x16, 0xd4, 0xa4, 0x5c, 0xcc, 0x5d, 0x65, 0xb6, 0x92,
    0x6c, 0x70, 0x48, 0x50, 0xfd, 0xed, 0xb9, 0xda, 0x5e, 0x15, 0x46, 0x57, 0xa7, 0x8d, 0x9d, 0x84,
    0x90, 0xd8, 0xab, 0x00, 0x8c, 0xbc, 0xd3, 0x0a, 0xf7, 0xe4, 0x58, 0x05, 0xb8, 0xb3, 0x45, 0x06,
    0xd0, 0x2c, 0x1e, 0x8f, 0xca, 0x3f, 0x0f, 0x02, 0xc1, 0xaf, 0xbd, 0x03, 0x01, 0x13, 0x8a, 0x6b,
    0x3a, 0x91, 0x11, 0x41, 0x4f, 0x67, 0xdc, 0xea, 0x97, 0xf2, 0xcf, 0xce, 0xf0, 0xb4, 0xe6, 0x73,
    0x96, 0xac, 0x74, 0x22, 0xe7, 0xad, 0x35, 0x85, 0xe2, 0xf9, 0x37, 0xe8, 0x1c, 0x75, 0xdf, 0x6e,
    0x47, 0xf1, 0x1a, 0x71, 0x1d, 0x29, 0xc5, 0x89, 0x6f, 0xb7, 0x62, 0x0e, 0xaa, 0x18, 0xbe, 0x1b,
    0xfc, 0x56, 0x3e, 0x4b, 0xc6, 0xd2, 0x79, 0x20, 0x9a, 0xdb, 0xc0, 0xfe, 0x78, 0xcd, 0x5a, 0xf4,
    0x1f, 0xdd, 0xa8, 0x33, 0x88, 0x07, 0xc7, 0x31, 0xb1, 0x12, 0x10, 0x59, 0x27, 0x80, 0xec, 0x5f,
    0x60, 0x51, 0x7f, 0xa9, 0x19, 0xb5, 0x4a, 0x0d, 0x2d, 0xe5, 0x7a, 0x9f, 0x93, 0xc9, 0x9c, 0xef,
    0xa0, 0xe0, 0x3b, 0x4d, 0xae, 0x2a, 0xf5, 0xb0, 0xc8, 0xeb, 0xbb, 0x3c, 0x83, 0x53, 0x99, 0x61,
    0x17, 0x2b, 0x04, 0x7e, 0xba, 0x77, 0xd6, 0x26, 0xe1, 0x69, 0x14, 0x63, 0x55, 0x21, 0x0c, 0x7d
]);

/*
 * RCON — round constants used by the AES-256 key schedule.
 *
 * Each value is the high byte of a 4-byte word; the other three bytes are 0.
 * The values are powers of x in GF(2^8): RCON[i] = x^(i+1) reduced by the
 * AES polynomial. AES-256 needs only 7 entries because the key schedule
 * applies a round constant once every 8 words, and there are 60 words in
 * the expanded key (60 = 8 + 7*8 + 4 leftover).
 */
const RCON = new Uint8Array([0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40]);


// ─────────────────────────────────────────────────────────────────────────────
// AES helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Multiply two bytes in GF(2^8) using the AES irreducible polynomial 0x11B.
 *
 * This is the "Russian peasant" or shift-and-XOR algorithm: walk the bits
 * of `b` from low to high; whenever a bit is set, XOR the running value of
 * `a` into the product; then double `a` (shift left by 1), reducing modulo
 * 0x11B whenever the shift would overflow 8 bits.
 *
 * Used only by mixColumns. Constants 2 and 3 cover all the multiplications
 * needed by encryption.
 */
function gmul(a, b) {
    let p = 0;
    for (let i = 0; i < 8; i++) {
        if (b & 1) p ^= a;
        const hi = a & 0x80;        // is the high bit set before doubling?
        a = (a << 1) & 0xff;        // double in GF(2^8) — i.e. shift left
        if (hi) a ^= 0x1b;          // reduction: x^8 = x^4+x^3+x+1, low byte = 0x1B
        b >>>= 1;
    }
    return p;
}

/**
 * SubBytes — substitute each of the 16 state bytes through the S-box.
 *
 * This is the only non-linear step in AES. Without it, AES would degenerate
 * to a system of linear equations over GF(2) and be trivially breakable.
 */
function subBytes(state) {
    for (let i = 0; i < 16; i++) {
        state[i] = S_BOX[state[i]];
    }
}

/**
 * ShiftRows — cyclically shift the rows of the 4x4 state matrix.
 *
 * The state is stored column-major in a 16-byte buffer:
 *
 *      column 0   column 1   column 2   column 3
 *   r0 state[0]   state[4]   state[8]   state[12]
 *   r1 state[1]   state[5]   state[9]   state[13]
 *   r2 state[2]   state[6]   state[10]  state[14]
 *   r3 state[3]   state[7]   state[11]  state[15]
 *
 * Row 0 stays put; row 1 rotates left by 1; row 2 by 2; row 3 by 3.
 * Together with MixColumns this provides the diffusion property — small
 * changes in one byte propagate to many bytes after a few rounds.
 */
function shiftRows(state) {
    // Row 1: left rotate by 1  →  [a,b,c,d] becomes [b,c,d,a]
    const t1 = state[1];
    state[1]  = state[5];
    state[5]  = state[9];
    state[9]  = state[13];
    state[13] = t1;

    // Row 2: left rotate by 2  →  [a,b,c,d] becomes [c,d,a,b]  (= two swaps)
    let t2 = state[2];  state[2]  = state[10]; state[10] = t2;
    t2     = state[6];  state[6]  = state[14]; state[14] = t2;

    // Row 3: left rotate by 3 (= right rotate by 1)
    const t3 = state[15];
    state[15] = state[11];
    state[11] = state[7];
    state[7]  = state[3];
    state[3]  = t3;
}

/**
 * MixColumns — multiply each column of the state by a fixed matrix in GF(2^8).
 *
 * For each column [s0, s1, s2, s3] the new column is:
 *
 *      [ 2 3 1 1 ] [ s0 ]
 *      [ 1 2 3 1 ] [ s1 ]
 *      [ 1 1 2 3 ] [ s2 ]
 *      [ 3 1 1 2 ] [ s3 ]
 *
 * The matrix coefficients are GF(2^8) field elements — multiplication is
 * done by `gmul`. This is the operation that mixes information *across*
 * rows; ShiftRows mixes across columns. Together they spread one input
 * byte's influence to all 16 output bytes after just two rounds.
 */
function mixColumns(state) {
    for (let c = 0; c < 4; c++) {
        const s0 = state[4 * c + 0];
        const s1 = state[4 * c + 1];
        const s2 = state[4 * c + 2];
        const s3 = state[4 * c + 3];

        state[4 * c + 0] = gmul(2, s0) ^ gmul(3, s1) ^ s2          ^ s3;
        state[4 * c + 1] = s0          ^ gmul(2, s1) ^ gmul(3, s2) ^ s3;
        state[4 * c + 2] = s0          ^ s1          ^ gmul(2, s2) ^ gmul(3, s3);
        state[4 * c + 3] = gmul(3, s0) ^ s1          ^ s2          ^ gmul(2, s3);
    }
}

/**
 * AddRoundKey — XOR the state with 16 bytes of the expanded key.
 *
 * The `round` argument selects which 16-byte slice of the expanded key to
 * use: round 0 uses bytes 0..15, round 1 uses 16..31, ..., round 14 uses
 * bytes 224..239. AES-256 has 14 rounds and 15 round keys (one before the
 * first round, one after each round).
 *
 * AddRoundKey is the *only* place where the key affects the state. Every
 * other step (SubBytes, ShiftRows, MixColumns) is keyless and the same
 * for every user — the entire security comes from the round keys.
 */
function addRoundKey(state, expandedKey, round) {
    const offset = round * 16;
    for (let i = 0; i < 16; i++) {
        state[i] ^= expandedKey[offset + i];
    }
}

/**
 * keyExpansion — expand a 32-byte key into a 240-byte round-key schedule.
 *
 * AES-256 derives 60 4-byte words (= 240 bytes = 15 round keys of 16 bytes)
 * from the 32-byte (= 8 word) input key. The first 8 words are the key
 * itself; each subsequent word `w[i]` is computed from `w[i-1]` and
 * `w[i-8]`, with two special cases:
 *
 *   - Every 8th word (i.e. i % 8 === 0): apply RotWord (cyclic byte
 *     rotation), then SubWord (S-box on each byte), then XOR the high
 *     byte with the next round constant.
 *   - Every 4th word offset by 4 (i % 8 === 4): SubWord only, no RotWord
 *     and no RCON.
 *
 * The "% 8 === 4" branch is unique to AES-256; AES-128 does not have it.
 */
function keyExpansion(key) {
    if (key.length !== 32) {
        throw new Error(`AES-256 keyExpansion: key must be 32 bytes (got ${key.length})`);
    }

    const N = 8;            // input key length in 32-bit words
    const TOTAL = 60;       // total words in the expanded key (15 round keys * 4 words)

    // Pack the 32 input bytes into eight big-endian 32-bit words.
    const w = new Array(TOTAL);
    for (let i = 0; i < N; i++) {
        w[i] = (
            (key[4 * i]     << 24) |
            (key[4 * i + 1] << 16) |
            (key[4 * i + 2] <<  8) |
             key[4 * i + 3]
        ) >>> 0;
    }

    for (let i = N; i < TOTAL; i++) {
        let temp = w[i - 1];

        if (i % N === 0) {
            // RotWord: rotate left by one byte.
            temp = ((temp << 8) | (temp >>> 24)) >>> 0;
            // SubWord: apply S-box to each byte.
            temp = (
                (S_BOX[(temp >>> 24) & 0xff] << 24) |
                (S_BOX[(temp >>> 16) & 0xff] << 16) |
                (S_BOX[(temp >>>  8) & 0xff] <<  8) |
                 S_BOX[ temp         & 0xff]
            ) >>> 0;
            // XOR the round constant into the high byte.
            // RCON is 0-indexed here; the round-key index uses (i / N - 1).
            temp = (temp ^ (RCON[(i / N) - 1] << 24)) >>> 0;
        } else if (i % N === 4) {
            // SubWord only — AES-256 specific extra mixing step.
            temp = (
                (S_BOX[(temp >>> 24) & 0xff] << 24) |
                (S_BOX[(temp >>> 16) & 0xff] << 16) |
                (S_BOX[(temp >>>  8) & 0xff] <<  8) |
                 S_BOX[ temp         & 0xff]
            ) >>> 0;
        }

        w[i] = (w[i - N] ^ temp) >>> 0;
    }

    // Serialize the 60 words back into a 240-byte buffer (big-endian).
    const expanded = Buffer.alloc(240);
    for (let i = 0; i < TOTAL; i++) {
        expanded.writeUInt32BE(w[i], i * 4);
    }
    return expanded;
}

/**
 * aesEncryptBlock — encrypt one 16-byte block under an expanded AES-256 key.
 *
 * The structure is:
 *   - AddRoundKey with round-key 0 (this is the only thing applied before
 *     the rounds proper)
 *   - 13 main rounds: SubBytes → ShiftRows → MixColumns → AddRoundKey(t)
 *   - 1 final round: SubBytes → ShiftRows → AddRoundKey(14)
 *     (the final round drops MixColumns, by design — it would not improve
 *     diffusion since the next AddRoundKey absorbs anything it could do)
 *
 * Returns a fresh 16-byte Buffer; does not mutate the input.
 */
function aesEncryptBlock(block, expandedKey) {
    if (block.length !== 16) {
        throw new Error(`aesEncryptBlock: block must be 16 bytes (got ${block.length})`);
    }

    // Make a working copy so the caller's input buffer stays untouched.
    const state = Buffer.from(block);

    addRoundKey(state, expandedKey, 0);

    for (let round = 1; round < 14; round++) {
        subBytes(state);
        shiftRows(state);
        mixColumns(state);
        addRoundKey(state, expandedKey, round);
    }

    // Final round — note the absence of MixColumns.
    subBytes(state);
    shiftRows(state);
    addRoundKey(state, expandedKey, 14);

    return state;
}


// ═════════════════════════════════════════════════════════════════════════════
//  PART B — GCM mode (NIST SP 800-38D)
// ═════════════════════════════════════════════════════════════════════════════


/**
 * ghashMultiply — multiply two 16-byte buffers as elements of GF(2^128) using
 * GCM's polynomial x^128 + x^7 + x^2 + x + 1 and GCM's bit ordering.
 *
 * Recall the bit-reversal convention: the leftmost bit of byte 0 of X is
 * the coefficient of x^0; the rightmost bit of byte 15 of X is the
 * coefficient of x^127.
 *
 * Algorithm: walk the bits of X from x^0 to x^127. Maintain a "shifted Y"
 * accumulator V that starts equal to Y and is multiplied by x after every
 * iteration. Whenever the current X bit is set, XOR V into the result Z.
 *
 * "Multiply V by x" is implemented as a *right* shift of the 128-bit buffer
 * (because of the bit-reversal convention), with the bit shifted out of
 * the LSB end triggering an XOR with 0xE1 in byte 0 to perform the
 * polynomial reduction.
 */
function ghashMultiply(X, Y) {
    const Z = Buffer.alloc(16);            // accumulator, starts at zero
    const V = Buffer.from(Y);              // running "Y * x^i", starts at Y

    for (let i = 0; i < 128; i++) {
        // Read bit i of X under GCM's convention:
        //   i=0 → byte 0, bit 7 (MSB)
        //   i=7 → byte 0, bit 0 (LSB)
        //   i=8 → byte 1, bit 7
        //   ...
        const xByte = i >>> 3;
        const xBit  = 7 - (i & 7);
        if ((X[xByte] >> xBit) & 1) {
            // Z ^= V
            for (let k = 0; k < 16; k++) Z[k] ^= V[k];
        }

        // V *= x  (right-shift the buffer by 1 bit, with reduction)
        const lsb = V[15] & 1;             // coefficient of x^127 before shift
        for (let k = 15; k > 0; k--) {
            V[k] = ((V[k] >>> 1) | ((V[k - 1] & 1) << 7)) & 0xff;
        }
        V[0] = (V[0] >>> 1) & 0xff;
        if (lsb) {
            // Reduction: bit fell off the high end → add x^128 mod P
            // = x^7 + x^2 + x + 1, which lives in byte 0 as 0xE1 in
            // GCM's bit-reversed encoding.
            V[0] ^= 0xe1;
        }
    }

    return Z;
}

/**
 * ghash — hash a sequence of 16-byte blocks under key H.
 *
 * Y starts at zero. For each block, XOR it into Y, then multiply Y by H.
 * The final Y is the hash. GCM uses this as a polynomial-evaluation hash:
 * if data is blocks B1, B2, ..., Bn, the result is
 *
 *      Y = B1·H^n + B2·H^(n-1) + ... + Bn·H   (in GF(2^128))
 *
 * `data` MUST already be a multiple of 16 bytes — pad it with zeros before
 * calling. We do this in the encrypt/decrypt routines via padToBlock.
 */
function ghash(H, data) {
    if (data.length % 16 !== 0) {
        throw new Error('ghash: data length must be a multiple of 16');
    }
    let Y = Buffer.alloc(16);              // accumulator starts at zero

    for (let offset = 0; offset < data.length; offset += 16) {
        // Y ^= block
        for (let k = 0; k < 16; k++) Y[k] ^= data[offset + k];
        // Y = Y * H   (in GF(2^128))
        Y = ghashMultiply(Y, H);
    }

    return Y;
}

/**
 * padToBlock — return a copy of `buf` zero-padded to the next 16-byte boundary.
 *
 * GCM's GHASH input format is "AAD padded || ciphertext padded || lengths".
 * Both the AAD and ciphertext sections must be a whole number of 16-byte
 * blocks; if either has a partial last block, the spec says to right-pad
 * with zeros up to the boundary.
 */
function padToBlock(buf) {
    const remainder = buf.length % 16;
    if (remainder === 0) return Buffer.from(buf);
    const padded = Buffer.alloc(buf.length + (16 - remainder));
    buf.copy(padded, 0);
    return padded;
}

/**
 * writeUInt64BE — write a non-negative integer as a 64-bit big-endian value.
 *
 * Buffer doesn't have a non-BigInt 64-bit BE writer, and BigInt is heavier
 * than we need. JavaScript numbers are exact up to 2^53, well above the
 * largest realistic message bit-length, so we just split into hi/lo halves.
 */
function writeUInt64BE(buf, offset, value) {
    const hi = Math.floor(value / 0x100000000);
    const lo = value >>> 0;
    buf.writeUInt32BE(hi, offset);
    buf.writeUInt32BE(lo, offset + 4);
}

/**
 * incrementCounter — increment the last 4 bytes of a 16-byte counter as a
 * big-endian 32-bit integer. The first 12 bytes (the IV portion) stay fixed.
 *
 * GCM uses this between successive blocks of the keystream: each block of
 * keystream is AES(counter), and the counter advances by 1 for the next
 * block. With a 32-bit counter we can encrypt up to 2^32 - 2 blocks under
 * one (key, IV) pair — about 64 GiB of data.
 */
function incrementCounter(counter) {
    const out = Buffer.from(counter);
    let carry = 1;
    for (let i = 15; i >= 12 && carry; i--) {
        const sum = out[i] + carry;
        out[i] = sum & 0xff;
        carry = sum >> 8;
    }
    return out;
}

/**
 * gctr — GCM counter mode encryption.
 *
 * Walk the input in 16-byte chunks. For each chunk:
 *   - encrypt the current counter to produce a 16-byte keystream block
 *   - XOR the keystream with the input chunk
 *   - increment the counter
 *
 * The last chunk may be shorter than 16 bytes; we use only as many keystream
 * bytes as we need. Decryption is the same operation (XOR is self-inverse).
 */
function gctr(expandedKey, initialCounter, input) {
    const output = Buffer.alloc(input.length);
    let counter = Buffer.from(initialCounter);

    let offset = 0;
    while (offset < input.length) {
        const keystream = aesEncryptBlock(counter, expandedKey);
        const blockLen  = Math.min(16, input.length - offset);
        for (let i = 0; i < blockLen; i++) {
            output[offset + i] = input[offset + i] ^ keystream[i];
        }
        counter = incrementCounter(counter);
        offset += blockLen;
    }

    return output;
}

/**
 * constantTimeEqual — XOR-and-OR comparison that does not short-circuit.
 *
 * For tag verification we cannot use Buffer.compare or === on hex strings:
 * those return as soon as they see the first different byte, which leaks
 * information about *where* the tag mismatched via timing. Walking every
 * byte with bitwise OR makes the comparison time depend only on length,
 * not on contents.
 */
function constantTimeEqual(a, b) {
    if (a.length !== b.length) return false;
    let diff = 0;
    for (let i = 0; i < a.length; i++) {
        diff |= a[i] ^ b[i];
    }
    return diff === 0;
}


// ─────────────────────────────────────────────────────────────────────────────
// Top-level entry points
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Coerce a string-or-Buffer into a Buffer (UTF-8 encoded for strings).
 * `null`/`undefined` are treated as empty input — handy for the optional
 * `aad` argument.
 */
function toBuffer(input, label) {
    if (input == null) return Buffer.alloc(0);
    if (Buffer.isBuffer(input)) return input;
    if (typeof input === 'string') return Buffer.from(input, 'utf8');
    throw new TypeError(`aes256gcm: ${label} must be a string, Buffer, or null/undefined`);
}

/**
 * Encrypt and authenticate `plaintext` under (`key`, `iv`), with optional
 * additional authenticated data `aad`.
 *
 * @param {Buffer}        key        — 32 bytes
 * @param {Buffer}        iv         — exactly 12 bytes (other lengths rejected)
 * @param {Buffer|string} plaintext  — any length, including 0
 * @param {Buffer|string} [aad]      — any length, including 0
 * @returns {{ciphertext: Buffer, tag: Buffer}} — ciphertext is same length as
 *           plaintext; tag is exactly 16 bytes
 */
function aes256gcmEncrypt(key, iv, plaintext, aad) {
    if (!Buffer.isBuffer(key) || key.length !== 32) {
        throw new Error('aes256gcmEncrypt: key must be a 32-byte Buffer');
    }
    if (!Buffer.isBuffer(iv) || iv.length !== 12) {
        throw new Error('aes256gcmEncrypt: iv must be a 12-byte Buffer (we restrict to the standard 12-byte IV path)');
    }

    const ptBuf  = toBuffer(plaintext, 'plaintext');
    const aadBuf = toBuffer(aad,       'aad');

    const expandedKey = keyExpansion(key);

    // Step 1: H = AES_K(0^128). H is the GHASH key.
    const H = aesEncryptBlock(Buffer.alloc(16), expandedKey);

    // Step 2: J0 = IV || 0x00000001    (12-byte IV path only)
    const J0 = Buffer.alloc(16);
    iv.copy(J0, 0);
    J0[15] = 0x01;

    // Step 3: encrypt with CTR starting at J0+1
    const initialCtr = incrementCounter(J0);
    const ciphertext = gctr(expandedKey, initialCtr, ptBuf);

    // Step 4: assemble the GHASH input
    //   AAD padded to next 16-byte boundary
    //   || ciphertext padded to next 16-byte boundary
    //   || (len(AAD) in bits as 64-bit BE) (len(CT) in bits as 64-bit BE)
    const lengthsBlock = Buffer.alloc(16);
    writeUInt64BE(lengthsBlock, 0, aadBuf.length     * 8);
    writeUInt64BE(lengthsBlock, 8, ciphertext.length * 8);

    const ghashInput = Buffer.concat([
        padToBlock(aadBuf),
        padToBlock(ciphertext),
        lengthsBlock
    ]);
    const S = ghash(H, ghashInput);

    // Step 5: tag = S XOR AES_K(J0)
    const J0Encrypted = aesEncryptBlock(J0, expandedKey);
    const tag = Buffer.alloc(16);
    for (let i = 0; i < 16; i++) tag[i] = S[i] ^ J0Encrypted[i];

    return { ciphertext, tag };
}

/**
 * Verify the authentication tag and (only on success) decrypt `ciphertext`
 * under (`key`, `iv`) with the same `aad` used at encrypt time.
 *
 * Throws 'GCM authentication failed' on any tag mismatch BEFORE any
 * plaintext is returned, so a caller cannot use this routine as a
 * decryption oracle.
 *
 * @param {Buffer}        key
 * @param {Buffer}        iv
 * @param {Buffer|string} ciphertext
 * @param {Buffer}        tag      — exactly 16 bytes
 * @param {Buffer|string} [aad]
 * @returns {Buffer} plaintext
 */
function aes256gcmDecrypt(key, iv, ciphertext, tag, aad) {
    if (!Buffer.isBuffer(key) || key.length !== 32) {
        throw new Error('aes256gcmDecrypt: key must be a 32-byte Buffer');
    }
    if (!Buffer.isBuffer(iv) || iv.length !== 12) {
        throw new Error('aes256gcmDecrypt: iv must be a 12-byte Buffer');
    }
    if (!Buffer.isBuffer(tag) || tag.length !== 16) {
        throw new Error('aes256gcmDecrypt: tag must be a 16-byte Buffer');
    }

    const ctBuf  = toBuffer(ciphertext, 'ciphertext');
    const aadBuf = toBuffer(aad,        'aad');

    const expandedKey = keyExpansion(key);

    // Reproduce H, J0, and the expected tag exactly as the encrypt side did.
    const H = aesEncryptBlock(Buffer.alloc(16), expandedKey);

    const J0 = Buffer.alloc(16);
    iv.copy(J0, 0);
    J0[15] = 0x01;

    const lengthsBlock = Buffer.alloc(16);
    writeUInt64BE(lengthsBlock, 0, aadBuf.length * 8);
    writeUInt64BE(lengthsBlock, 8, ctBuf.length  * 8);

    const ghashInput = Buffer.concat([
        padToBlock(aadBuf),
        padToBlock(ctBuf),
        lengthsBlock
    ]);
    const S = ghash(H, ghashInput);

    const J0Encrypted = aesEncryptBlock(J0, expandedKey);
    const expectedTag = Buffer.alloc(16);
    for (let i = 0; i < 16; i++) expectedTag[i] = S[i] ^ J0Encrypted[i];

    // Verify BEFORE producing plaintext — never expose the keystream to a
    // caller who supplied a bad tag.
    if (!constantTimeEqual(expectedTag, tag)) {
        throw new Error('GCM authentication failed');
    }

    // Tag is good — decrypt by running CTR mode again (same operation as encrypt).
    const initialCtr = incrementCounter(J0);
    return gctr(expandedKey, initialCtr, ctBuf);
}


module.exports = { aes256gcmEncrypt, aes256gcmDecrypt };


// ─────────────────────────────────────────────────────────────────────────────
// Self-test — runs only when this file is executed directly:
//   node aes256gcm.js
// Three NIST SP 800-38D appendix B test vectors. Each checks both the
// ciphertext and the authentication tag. All three should print PASS.
// We additionally round-trip every vector through aes256gcmDecrypt to
// confirm the decrypt path agrees with the encrypt path.
// ─────────────────────────────────────────────────────────────────────────────
if (require.main === module) {
    const vectors = [
        {
            name:        'NIST #1 (empty PT, empty AAD)',
            key:         Buffer.alloc(32),
            iv:          Buffer.alloc(12),
            plaintext:   Buffer.alloc(0),
            aad:         Buffer.alloc(0),
            expectedCt:  '',
            expectedTag: '530f8afbc74536b9a963b4f1c4cb738b'
        },
        {
            name:        'NIST #2 (16-byte zero PT, empty AAD)',
            key:         Buffer.alloc(32),
            iv:          Buffer.alloc(12),
            plaintext:   Buffer.alloc(16),
            aad:         Buffer.alloc(0),
            expectedCt:  'cea7403d4d606b6e074ec5d3baf39d18',
            expectedTag: 'd0d1c8a799996bf0265b98b5d48ab919'
        },
        {
            name:        'NIST #3 (60-byte PT + 20-byte AAD)',
            key:         Buffer.from('feffe9928665731c6d6a8f9467308308feffe9928665731c6d6a8f9467308308', 'hex'),
            iv:          Buffer.from('cafebabefacedbaddecaf888', 'hex'),
            plaintext:   Buffer.from(
                'd9313225f88406e5a55909c5aff5269a' +
                '86a7a9531534f7da2e4c303d8a318a72' +
                '1c3c0c95956809532fcf0e2449a6b525' +
                'b16aedf5aa0de657ba637b39',
                'hex'
            ),
            aad:         Buffer.from('feedfacedeadbeeffeedfacedeadbeefabaddad2', 'hex'),
            expectedCt:  '522dc1f099567d07f47f37a32a84427d' +
                         '643a8cdcbfe5c0c97598a2bd2555d1aa' +
                         '8cb08e48590dbb3da7b08b1056828838' +
                         'c5f61e6393ba7a0abcc9f662',
            expectedTag: '76fc6ece0f4e1768cddf8853bb2d551b'
        }
    ];

    let allPass = true;
    for (const v of vectors) {
        const { ciphertext, tag } = aes256gcmEncrypt(v.key, v.iv, v.plaintext, v.aad);
        const ctHex  = ciphertext.toString('hex');
        const tagHex = tag.toString('hex');
        const ctOk   = ctHex  === v.expectedCt;
        const tagOk  = tagHex === v.expectedTag;

        // Round-trip: decrypt should yield the original plaintext, and a tag
        // tampered by 1 byte must throw 'GCM authentication failed'.
        let roundTripOk = false;
        let rejectsBadTag = false;
        try {
            const decrypted = aes256gcmDecrypt(v.key, v.iv, ciphertext, tag, v.aad);
            roundTripOk = Buffer.compare(decrypted, v.plaintext) === 0;
        } catch { /* roundTripOk stays false */ }
        try {
            const badTag = Buffer.from(tag);
            badTag[0] ^= 0x01;
            aes256gcmDecrypt(v.key, v.iv, ciphertext, badTag, v.aad);
        } catch (err) {
            rejectsBadTag = err.message === 'GCM authentication failed';
        }

        const pass = ctOk && tagOk && roundTripOk && rejectsBadTag;
        if (!pass) allPass = false;

        console.log(`${pass ? 'PASS' : 'FAIL'}  ${v.name}`);
        if (!pass) {
            if (!ctOk) {
                console.log(`        ciphertext expected: ${v.expectedCt}`);
                console.log(`        ciphertext got:      ${ctHex}`);
            }
            if (!tagOk) {
                console.log(`        tag expected: ${v.expectedTag}`);
                console.log(`        tag got:      ${tagHex}`);
            }
            if (!roundTripOk)   console.log(`        decrypt round-trip did not recover plaintext`);
            if (!rejectsBadTag) console.log(`        decrypt did NOT reject a tampered tag — security failure`);
        }
    }

    process.exit(allPass ? 0 : 1);
}
