'use strict';

/*
 * ECDSA on the NIST P-256 curve (also called secp256r1 or prime256v1),
 * implemented from scratch using only BigInt arithmetic.
 *
 * What ECC actually is
 * ─────────────────────────────────────────────────────────────────────────────
 * Elliptic curve cryptography uses the algebraic structure of points on a
 * curve of the form
 *
 *     y² = x³ + a·x + b   (over a finite field GF(p))
 *
 * This isn't an equation about real-number ellipses — it's the same
 * equation interpreted in modular arithmetic. The set of (x, y) pairs
 * satisfying it (plus a "point at infinity" sentinel) forms a finite
 * abelian group under a geometric "addition" operation. The group is
 * cyclic, generated by a fixed base point G defined as part of the curve.
 *
 * The cryptographic security comes from the *discrete log problem*: given
 * a public point Q = k·G, computing the secret scalar k is conjectured
 * to be intractable. The best known classical algorithm (Pollard's rho)
 * runs in O(√n) where n is the group order. For n ≈ 2^256, that's 2^128
 * operations — comfortably out of reach.
 *
 * Why ECC instead of RSA
 * ─────────────────────────────────────────────────────────────────────────────
 * Smaller keys at equivalent security:
 *
 *     RSA bits   ECC bits   security
 *     ────────   ────────   ────────
 *     1024       160        ~80 bits
 *     2048       224        ~112 bits
 *     3072       256        ~128 bits   ← P-256, our choice
 *     7680       384        ~192 bits
 *
 * P-256 (256-bit ECC) gives roughly the same security as 3072-bit RSA, but
 * with much faster operations and tiny keys (32 bytes per coordinate vs
 * 384 bytes for an RSA modulus).
 *
 * Point addition and doubling — the geometric picture
 * ─────────────────────────────────────────────────────────────────────────────
 * Two distinct points P and Q on the curve are added by:
 *   1. Drawing the line through P and Q.
 *   2. Finding the (unique) third point where that line intersects the curve.
 *   3. Reflecting that third point across the x-axis. The result is P + Q.
 *
 * Doubling P (i.e., computing 2P = P + P) replaces the chord with the
 * tangent line at P. Same procedure: find third intersection, reflect.
 *
 * Both operations boil down to a few field operations involving the slope
 * λ. We implement them in AFFINE coordinates — the (x, y) pairs you
 * actually visualize. Real production libraries use Jacobian coordinates
 * to avoid the field inversions that affine requires, at the cost of
 * obscuring the geometry. We pick clarity.
 *
 * Scalar multiplication via double-and-add
 * ─────────────────────────────────────────────────────────────────────────────
 * k·P (the point P added to itself k times) is computed via the same
 * binary-exponentiation pattern we used for modular exponentiation in RSA:
 *
 *     5·P = 2·(2·P) + P                      (binary 101)
 *     6·P = 2·(2·P + P)                      (binary 110)
 *     7·P = 2·(2·P + P) + P                  (binary 111)
 *
 * Walk the bits of k from high to low; at each step double the running
 * accumulator and conditionally add P if the current bit is 1. Cost is
 * O(log k) point operations.
 *
 * ECDSA at a glance
 * ─────────────────────────────────────────────────────────────────────────────
 * Sign:
 *   - z = SHA-256(message)
 *   - Pick a fresh random ephemeral scalar k in [1, n-1]
 *   - Compute kG. Set r = (kG.x) mod n.
 *   - Set s = k⁻¹ · (z + r·d) mod n,  where d is the private scalar
 *   - Signature is (r, s)
 *
 * Verify:
 *   - Range-check r and s in [1, n-1]; check publicKey is a valid curve point
 *   - z = SHA-256(message)
 *   - w = s⁻¹ mod n; u1 = z·w mod n; u2 = r·w mod n
 *   - Compute the point u1·G + u2·Q
 *   - Accept iff (resulting point's x coordinate) mod n == r
 *
 * The k must be fresh (Sony PS3 lesson)
 * ─────────────────────────────────────────────────────────────────────────────
 * The ephemeral scalar k is the single most important secret in ECDSA.
 * It must be unpredictable AND fresh per signature. If two signatures
 * (r, s1) and (r, s2) under the same private key share the same k, then
 *
 *     k = (z1 - z2) · (s1 - s2)⁻¹ mod n
 *     d = (s1·k - z1) · r⁻¹ mod n
 *
 * — that is, the private key falls out in two short modular operations.
 * Sony famously hardcoded k in the PS3's firmware-signing code in 2010,
 * and the entire console signing key was extracted within hours of public
 * disclosure. We take k from crypto.randomBytes; never seed, never reuse.
 *
 * Invalid-curve attacks and why we validate every public key
 * ─────────────────────────────────────────────────────────────────────────────
 * If a verifier accepts a "public key" without checking it lies on the
 * intended curve, an attacker can submit a point that lies on a *different*
 * curve with weak structure (small subgroup), do scalar multiplications,
 * and recover information about the private key. We check
 * isOnCurve(publicKey) AND publicKey ≠ ∞ before any verification work.
 *
 * Allowed dependencies
 * ─────────────────────────────────────────────────────────────────────────────
 *   ./sha256          — used to hash messages before signing/verifying
 *   crypto.randomBytes — entropy for d and k (scalars and ephemeral k)
 */

const { sha256 } = require('./sha256');
const crypto     = require('crypto');   // randomBytes only


// ═════════════════════════════════════════════════════════════════════════════
//  PART A — Curve constants and BigInt math helpers
// ═════════════════════════════════════════════════════════════════════════════

/*
 * P-256 (secp256r1 / prime256v1) parameters from FIPS 186-4 / SEC 2.
 *
 *   p   field prime, equal to 2^256 - 2^224 + 2^192 + 2^96 - 1
 *   a   curve coefficient, equal to -3 mod p
 *   b   curve coefficient, a fixed verifiably-random NIST constant
 *   Gx  x-coordinate of the standard base point
 *   Gy  y-coordinate of the standard base point
 *   n   order of G (the smallest positive integer such that n·G = ∞)
 *   h   cofactor; equals 1 for P-256, meaning the curve group has prime
 *       order, so we don't need to worry about small subgroup attacks
 */
const p  = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffffn;
const a  = 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffcn;  // ≡ -3 (mod p)
const b  = 0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604bn;
const Gx = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296n;
const Gy = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5n;
const n  = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551n;
const h  = 1n;

/** The standard base point G as a {x, y} object. */
const G = { x: Gx, y: Gy };

/*
 * Coordinate width: every P-256 scalar and field element fits in 256 bits =
 * 32 bytes. We use this constant for fixed-width buffer encoding.
 */
const COORD_BYTES = 32;


/**
 * Interpret a big-endian Buffer as an unsigned BigInt.
 */
function bigIntFromBuffer(buf) {
    if (!Buffer.isBuffer(buf)) {
        throw new TypeError('bigIntFromBuffer: input must be a Buffer');
    }
    let n = 0n;
    for (let i = 0; i < buf.length; i++) {
        n = (n << 8n) | BigInt(buf[i]);
    }
    return n;
}

/**
 * Encode an unsigned BigInt as a fixed-size big-endian Buffer
 * (default 32 bytes for P-256 coordinates and scalars).
 */
function bigIntToBuffer(value, byteLength = COORD_BYTES) {
    if (value < 0n) throw new RangeError('bigIntToBuffer: value must be non-negative');
    const out = Buffer.alloc(byteLength);
    let temp = value;
    for (let i = byteLength - 1; i >= 0; i--) {
        out[i] = Number(temp & 0xffn);
        temp >>= 8n;
    }
    if (temp !== 0n) {
        throw new RangeError(`bigIntToBuffer: value does not fit in ${byteLength} bytes`);
    }
    return out;
}

/**
 * Modular exponentiation: returns base^exponent mod modulus.
 *
 * Same square-and-multiply as in rsa.js — duplicated here so this file
 * is self-contained (the constraint allows only ./sha256 + crypto).
 */
function modPow(base, exponent, modulus) {
    if (modulus === 1n) return 0n;
    if (exponent < 0n) throw new RangeError('modPow: negative exponent');

    let result = 1n;
    let bb = base % modulus;
    if (bb < 0n) bb += modulus;
    let ee = exponent;

    while (ee > 0n) {
        if (ee & 1n) result = (result * bb) % modulus;
        ee >>= 1n;
        bb = (bb * bb) % modulus;
    }
    return result;
}

/**
 * Modular inverse via Fermat's little theorem: x^(m-2) mod m.
 *
 * Only works when m is prime — but for ECDSA both p (the field prime) and
 * n (the group order) ARE prime, so this is exactly what we need. It's
 * shorter and clearer than the extended Euclidean algorithm at the cost
 * of one extra modPow call.
 */
function modInverse(value, modulus) {
    return modPow(value, modulus - 2n, modulus);
}

/**
 * Generate a uniformly random BigInt in [0, max). Rejection sampling.
 */
function randomBigIntInRange(max) {
    if (max <= 0n) throw new RangeError('randomBigIntInRange: max must be positive');
    const bits = max.toString(2).length;
    while (true) {
        const byteLength = Math.ceil(bits / 8);
        const buf        = crypto.randomBytes(byteLength);
        const topZeros   = byteLength * 8 - bits;
        buf[0] &= (0xff >>> topZeros);
        const candidate = bigIntFromBuffer(buf);
        if (candidate < max) return candidate;
    }
}

/**
 * Constant-time byte comparison. Provided as a utility; not actively used
 * in verifyECDSA because all the values it would compare there are public
 * (x mod n vs r are both derivable from the public signature + public key,
 * so timing leaks aren't a concern). Useful if you ever need to compare
 * a candidate signature against a stored one without a timing side channel.
 */
function constantTimeEqual(a, b) {
    if (!Buffer.isBuffer(a) || !Buffer.isBuffer(b)) return false;
    if (a.length !== b.length) return false;
    let diff = 0;
    for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
    return diff === 0;
}


// ═════════════════════════════════════════════════════════════════════════════
//  PART B — Field arithmetic in GF(p)
// ═════════════════════════════════════════════════════════════════════════════

/**
 * fAdd — addition in the prime field GF(p).
 */
function fAdd(x, y) {
    return (x + y) % p;
}

/**
 * fSub — subtraction in GF(p), normalized to the non-negative range [0, p).
 *
 * BigInt's `%` can produce negative results when the dividend is negative;
 * we add p to bring the result into [0, p) for canonical comparisons.
 */
function fSub(x, y) {
    let r = (x - y) % p;
    if (r < 0n) r += p;
    return r;
}

/**
 * fMul — multiplication in GF(p).
 */
function fMul(x, y) {
    return (x * y) % p;
}

/**
 * fSquare — squaring in GF(p). Wrapping fMul, but called out as its own
 * function because the curve formulas have many "x²" terms and writing
 * fSquare(x) is more readable than fMul(x, x).
 */
function fSquare(x) {
    return (x * x) % p;
}

/**
 * fInverse — modular inverse in GF(p), using Fermat's little theorem.
 * Equivalent to x^(p-2) mod p.
 *
 * Each curve operation (pointAdd, pointDouble) requires one of these,
 * which is the dominant cost of affine-coordinate ECC.
 */
function fInverse(x) {
    return modPow(x, p - 2n, p);
}

/**
 * fNeg — additive inverse (negation) in GF(p): returns p - x mod p.
 *
 * Geometrically, on an elliptic curve the negative of a point (x, y) is
 * (x, -y); fNeg is what computes the y-coordinate flip.
 */
function fNeg(x) {
    return (p - (x % p)) % p;
}


// ═════════════════════════════════════════════════════════════════════════════
//  PART C — Point arithmetic in affine coordinates
// ═════════════════════════════════════════════════════════════════════════════

/*
 * Throughout this section, a "point" is either:
 *   - an object { x: BigInt, y: BigInt } representing an affine (x, y), or
 *   - the JavaScript value `null`, representing the point at infinity ∞
 *     (the identity element of the elliptic curve group).
 */

/**
 * isInfinity — is this point ∞?
 */
function isInfinity(P) {
    return P === null;
}

/**
 * pointEquals — structural equality of two points.
 */
function pointEquals(P, Q) {
    if (P === null && Q === null) return true;
    if (P === null || Q === null) return false;
    return P.x === Q.x && P.y === Q.y;
}

/**
 * isOnCurve — does P satisfy y² ≡ x³ + a·x + b (mod p)?
 *
 * The point at infinity is, by mathematical convention, on every elliptic
 * curve (it is the group identity). We return `true` for null to match
 * that convention; the verify code separately rejects ∞ as a public key.
 *
 * Used to validate public keys before using them in verification — the
 * defense against invalid-curve attacks.
 */
function isOnCurve(P) {
    if (P === null) return true;

    const lhs = fSquare(P.y);
    const xCubed = fMul(fSquare(P.x), P.x);
    const ax     = fMul(a, P.x);
    const rhs    = fAdd(fAdd(xCubed, ax), b);

    return lhs === rhs;
}

/**
 * pointDouble — compute 2·P.
 *
 * Tangent-line slope:  λ = (3·Px² + a) / (2·Py)
 * Result:              xR = λ² - 2·Px
 *                      yR = λ·(Px - xR) - Py
 *
 * If Py is 0 the tangent is vertical and 2·P = ∞. (Doesn't happen for the
 * standard P-256 base point, but we handle it for completeness.)
 */
function pointDouble(P) {
    if (P === null) return null;
    if (P.y === 0n) return null;

    const num    = fAdd(fMul(3n, fSquare(P.x)), a);
    const den    = fMul(2n, P.y);
    const lambda = fMul(num, fInverse(den));

    const xR = fSub(fSquare(lambda), fMul(2n, P.x));
    const yR = fSub(fMul(lambda, fSub(P.x, xR)), P.y);

    return { x: xR, y: yR };
}

/**
 * pointAdd — compute P + Q.
 *
 * Several special cases must be handled before the generic chord-slope
 * formula applies:
 *   - if either point is ∞, return the other one (∞ is the identity);
 *   - if they share an x-coordinate but have opposite y, they're additive
 *     inverses and the sum is ∞;
 *   - if they're equal, the chord becomes a tangent → delegate to
 *     pointDouble (otherwise the formula divides by zero);
 *   - otherwise: λ = (Qy - Py) / (Qx - Px)
 *               xR = λ² - Px - Qx
 *               yR = λ·(Px - xR) - Py
 */
function pointAdd(P, Q) {
    if (P === null) return Q;
    if (Q === null) return P;

    if (P.x === Q.x) {
        if (P.y === Q.y) return pointDouble(P);
        // P.y ≡ -Q.y (mod p) → result is the point at infinity
        return null;
    }

    const num    = fSub(Q.y, P.y);
    const den    = fSub(Q.x, P.x);
    const lambda = fMul(num, fInverse(den));

    const xR = fSub(fSub(fSquare(lambda), P.x), Q.x);
    const yR = fSub(fMul(lambda, fSub(P.x, xR)), P.y);

    return { x: xR, y: yR };
}

/**
 * scalarMultiply — compute k·P via double-and-add.
 *
 * Walk the bits of k from most-significant to least-significant. At each
 * step double the running accumulator; if the current bit of k is 1, add
 * P. Same recipe as binary exponentiation in modular arithmetic, but with
 * point addition substituted for multiplication.
 *
 * Returns ∞ (null) if k is 0 or if P itself is ∞.
 */
function scalarMultiply(k, P) {
    if (k < 0n) throw new RangeError('scalarMultiply: scalar must be non-negative');
    if (k === 0n || P === null) return null;

    let result   = null;                             // start at ∞
    const bitLen = k.toString(2).length;

    for (let i = bitLen - 1; i >= 0; i--) {
        result = pointDouble(result);
        if ((k >> BigInt(i)) & 1n) {
            result = pointAdd(result, P);
        }
    }

    return result;
}


// ═════════════════════════════════════════════════════════════════════════════
//  PART D — ECDSA sign / verify, plus DER encoding helpers
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Modular inverse mod the GROUP ORDER n (not the field prime p). Used
 * inside ECDSA where we work in the scalar field, not the coordinate field.
 */
function modInverseN(value) {
    return modInverse(value, n);
}

/**
 * Generate a fresh ECDSA keypair.
 *
 * @returns {{d: bigint, Q: {x: bigint, y: bigint}}}  d is the private
 * scalar in [1, n-1]; Q = d·G is the public point.
 */
function generateECCKeyPair() {
    // d in [1, n-1] inclusive: pick d in [0, n-1) and add 1.
    const d = 1n + randomBigIntInRange(n - 1n);
    const Q = scalarMultiply(d, G);
    return { d, Q };
}

/**
 * Hash a message to a scalar (FIPS 186-4 §6.4 / RFC 6979 §2.3.2).
 *
 * For SHA-256 + P-256 the hash output (256 bits) is exactly the same
 * length as n, so no leftmost-bits truncation is needed; we just take
 * the integer value mod n. (For SHA-512 + P-256 you would truncate to
 * 256 bits before reducing.)
 */
function hashMessage(message) {
    const msgBuf = Buffer.isBuffer(message) ? message : Buffer.from(message, 'utf8');
    const h      = sha256(msgBuf);
    return bigIntFromBuffer(h) % n;
}

/**
 * Produce an ECDSA signature (r, s) for `message` under the private key `d`.
 *
 * Loop until we get a non-zero r and s — both can fail to be non-zero
 * with probability roughly 2^-256 each, so in practice the loop runs
 * exactly once. We still loop because the spec requires it.
 *
 * IMPORTANT: a fresh random k must be generated for each signature — see
 * the file header on the Sony PS3 incident.
 */
function signECDSA(message, privateKey) {
    if (typeof privateKey !== 'bigint') {
        throw new TypeError('signECDSA: privateKey must be a BigInt scalar');
    }
    if (privateKey < 1n || privateKey >= n) {
        throw new RangeError('signECDSA: privateKey out of range [1, n-1]');
    }

    const z = hashMessage(message);

    while (true) {
        const k  = 1n + randomBigIntInRange(n - 1n);
        const kG = scalarMultiply(k, G);
        if (kG === null) continue;          // astronomically unlikely

        const r = kG.x % n;
        if (r === 0n) continue;

        const kInv = modInverseN(k);
        const s    = (kInv * (z + r * privateKey)) % n;
        if (s === 0n) continue;

        return { r, s };
    }
}

/**
 * Verify an ECDSA signature (`{r, s}`) on `message` under public point Q.
 *
 * Returns boolean. Performs all the standard mandatory checks:
 *   - r and s are integers in [1, n-1]
 *   - Q is well-formed and lies on the curve
 *   - Q is not the point at infinity
 * before doing any signature math. This is the invalid-curve-attack
 * defense referenced in the file header.
 */
function verifyECDSA(message, signature, publicKey) {
    // Argument shape checks — fail closed on any malformed input.
    if (!signature || typeof signature !== 'object') return false;
    const { r, s } = signature;
    if (typeof r !== 'bigint' || typeof s !== 'bigint') return false;

    // Range checks: r, s in [1, n-1]
    if (r < 1n || r >= n) return false;
    if (s < 1n || s >= n) return false;

    // Public key validity
    if (publicKey === null || typeof publicKey !== 'object') return false;
    if (typeof publicKey.x !== 'bigint' || typeof publicKey.y !== 'bigint') return false;
    if (!isOnCurve(publicKey)) return false;
    // (P-256 has cofactor 1, so any non-∞ on-curve point is automatically in
    // the prime-order subgroup — no separate subgroup check needed.)

    const z  = hashMessage(message);
    const w  = modInverseN(s);
    const u1 = (z * w) % n;
    const u2 = (r * w) % n;

    const X = pointAdd(scalarMultiply(u1, G), scalarMultiply(u2, publicKey));
    if (X === null) return false;

    return (X.x % n) === r;
}


// ─────────────────────────────────────────────────────────────────────────────
// DER encoding for ECDSA signatures
//
// Node's crypto.createSign('SHA256').sign(privateKey) returns ECDSA
// signatures in ASN.1 DER format by default. To interop we need the same
// encoding. The wire format for an ECDSA signature is:
//
//     SEQUENCE {
//         INTEGER r
//         INTEGER s
//     }
//
// In ASN.1 DER:
//   - SEQUENCE is tag 0x30
//   - INTEGER  is tag 0x02
//   - Each value is preceded by its length byte (short-form < 128)
//   - INTEGER values are minimum-length two's-complement, big-endian:
//       * Strip leading zero bytes,
//       * BUT if the high bit of the resulting first byte is set, prepend
//         one 0x00 byte to keep the value unambiguously non-negative.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Encode a non-negative BigInt as a DER INTEGER (tag + length + bytes).
 */
function encodeDERInteger(value) {
    if (value < 0n) throw new RangeError('DER INTEGER: value must be non-negative');

    // Convert to minimum-length big-endian bytes.
    let hex = value.toString(16);
    if (hex.length % 2 === 1) hex = '0' + hex;
    let bytes = Buffer.from(hex, 'hex');

    // Edge case: value is 0 → encode as a single 0x00 byte.
    if (bytes.length === 0) bytes = Buffer.from([0x00]);

    // Strip leading zeros (but always keep at least one byte).
    while (bytes.length > 1 && bytes[0] === 0x00) {
        bytes = bytes.subarray(1);
    }

    // If the high bit is set, prepend 0x00 so the value is interpreted
    // as positive (DER INTEGERs are signed).
    if (bytes[0] & 0x80) {
        bytes = Buffer.concat([Buffer.from([0x00]), bytes]);
    }

    return Buffer.concat([Buffer.from([0x02, bytes.length]), bytes]);
}

/**
 * Read a DER INTEGER (tag + length + bytes) and return [value, totalConsumed].
 */
function decodeDERInteger(buf, offset) {
    if (buf[offset] !== 0x02) throw new Error('DER: expected INTEGER tag (0x02)');
    const len = buf[offset + 1];
    if (len & 0x80) throw new Error('DER: long-form length not supported (signature too large)');
    const bytes = buf.subarray(offset + 2, offset + 2 + len);
    const value = bigIntFromBuffer(bytes);
    return [value, 2 + len];
}

/**
 * Encode an ECDSA signature as ASN.1 DER.
 */
function signatureToDER(signature) {
    const rDer  = encodeDERInteger(signature.r);
    const sDer  = encodeDERInteger(signature.s);
    const inner = Buffer.concat([rDer, sDer]);

    if (inner.length >= 0x80) {
        // For P-256 signatures this can't happen (max inner length is ~70).
        throw new Error('DER: inner length exceeds short-form limit');
    }
    return Buffer.concat([Buffer.from([0x30, inner.length]), inner]);
}

/**
 * Decode an ASN.1 DER ECDSA signature into {r, s}.
 */
function signatureFromDER(buf) {
    if (!Buffer.isBuffer(buf)) {
        throw new TypeError('signatureFromDER: input must be a Buffer');
    }
    if (buf.length < 8 || buf[0] !== 0x30) {
        throw new Error('DER: expected SEQUENCE tag (0x30)');
    }
    const seqLen = buf[1];
    if (seqLen & 0x80) throw new Error('DER: long-form length not supported');
    if (seqLen + 2 !== buf.length) throw new Error('DER: SEQUENCE length mismatch');

    let i = 2;
    const [r, rConsumed] = decodeDERInteger(buf, i); i += rConsumed;
    const [s, sConsumed] = decodeDERInteger(buf, i); i += sConsumed;

    if (i !== buf.length) throw new Error('DER: trailing bytes after s');

    return { r, s };
}

/**
 * Convenience: sign with ECDSA and return the DER-encoded signature Buffer.
 */
function signECDSADER(message, privateKey) {
    return signatureToDER(signECDSA(message, privateKey));
}

/**
 * Convenience: verify a DER-encoded ECDSA signature Buffer.
 */
function verifyECDSADER(message, derBuf, publicKey) {
    let signature;
    try { signature = signatureFromDER(derBuf); }
    catch { return false; }
    return verifyECDSA(message, signature, publicKey);
}


module.exports = {
    // Curve parameters (read-only — exposed for tests and interop)
    CURVE: { p, a, b, n, h, G, COORD_BYTES },

    // Math helpers
    bigIntFromBuffer,
    bigIntToBuffer,
    modPow,
    modInverse,
    randomBigIntInRange,
    constantTimeEqual,

    // Point arithmetic (exposed mostly for tests)
    isInfinity,
    isOnCurve,
    pointEquals,
    pointAdd,
    pointDouble,
    scalarMultiply,

    // ECDSA
    generateECCKeyPair,
    signECDSA,
    verifyECDSA,
    signECDSADER,
    verifyECDSADER,
    signatureToDER,
    signatureFromDER
};


// ─────────────────────────────────────────────────────────────────────────────
// Self-test — runs only when this file is executed directly:
//   node ecdsaP256.js
// ─────────────────────────────────────────────────────────────────────────────
if (require.main === module) {
    let allPass = true;

    function record(name, pass, detail) {
        if (!pass) allPass = false;
        console.log(`${pass ? 'PASS' : 'FAIL'}  ${name}`);
        if (!pass && detail) console.log(`        ${detail}`);
    }

    // ── Test 1: standard base point lies on the curve ───────────────────
    {
        record('Test 1: base point G satisfies y² ≡ x³ + a·x + b (mod p)',
            isOnCurve(G));
    }

    // ── Test 2: n·G is the point at infinity ────────────────────────────
    {
        // This single check exercises every branch of pointAdd/pointDouble
        // across the full 256 bits of the group order. If field or point
        // arithmetic had any bug, this is the test most likely to catch it.
        const result = scalarMultiply(n, G);
        record('Test 2: n·G is the point at infinity',
            isInfinity(result),
            result ? `got x=${result.x.toString(16).slice(0, 16)}…` : '');
    }

    // ── Test 3: doubling and same-point addition agree ──────────────────
    {
        const G2viaDouble = pointDouble(G);
        const G2viaAdd    = pointAdd(G, G);
        const onCurve     = isOnCurve(G2viaDouble) && isOnCurve(G2viaAdd);
        const equal       = pointEquals(G2viaDouble, G2viaAdd);
        record('Test 3: 2G via pointDouble equals 2G via pointAdd(G,G)',
            onCurve && equal,
            `onCurve=${onCurve} equal=${equal}`);
    }

    // ── Test 4: ECDSA sign + verify round-trip + rejection cases ────────
    let keypair, validSig;
    {
        keypair  = generateECCKeyPair();
        validSig = signECDSA('hello world', keypair.d);

        const acceptCorrect = verifyECDSA('hello world', validSig, keypair.Q);
        const rejectWrongMsg = !verifyECDSA('hello other', validSig, keypair.Q);

        // Tamper s by adding 1 (mod n)
        const tamperedSig    = { r: validSig.r, s: (validSig.s + 1n) % n };
        const rejectTampered = !verifyECDSA('hello world', tamperedSig, keypair.Q);

        record('Test 4: ECDSA round-trip + rejects wrong message + rejects tampered s',
            acceptCorrect && rejectWrongMsg && rejectTampered,
            `accept=${acceptCorrect} rejectWrong=${rejectWrongMsg} rejectTampered=${rejectTampered}`);
    }

    // ── Test 5: signatures are non-deterministic ────────────────────────
    {
        const sig1 = signECDSA('hello world', keypair.d);
        const sig2 = signECDSA('hello world', keypair.d);
        const different = sig1.r !== sig2.r || sig1.s !== sig2.s;
        // Both should still verify
        const bothValid = verifyECDSA('hello world', sig1, keypair.Q) &&
                          verifyECDSA('hello world', sig2, keypair.Q);
        record('Test 5: two signatures of the same message differ (fresh k each call)',
            different && bothValid,
            `different=${different} bothValid=${bothValid}`);
    }

    // ── Test 6: DER encoding round-trip, both high-bit cases ────────────
    {
        // Case A — both r and s have high bit CLEAR (no leading-zero pad needed)
        const sigClear = {
            r: 0x12abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234567n,
            s: 0x7fedcba987654321fedcba987654321fedcba987654321fedcba987654321febn
        };
        // Case B — both r and s have high bit SET (each needs leading 0x00 pad)
        const sigSet = {
            r: 0xfedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210n,
            s: 0x80abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234567n
        };

        const derClear  = signatureToDER(sigClear);
        const backClear = signatureFromDER(derClear);
        const derSet    = signatureToDER(sigSet);
        const backSet   = signatureFromDER(derSet);

        const clearRoundTrip = backClear.r === sigClear.r && backClear.s === sigClear.s;
        const setRoundTrip   = backSet.r === sigSet.r && backSet.s === sigSet.s;

        // Confirm the high-bit-set encoding actually inserts a leading 0x00:
        //   SEQUENCE(0x30) length INTEGER(0x02) integerLen <integerBytes>
        // For 32-byte r with high bit set, integerLen is 33 (0x21) and the
        // first integer byte after the length must be 0x00.
        const setEncodingHasLeadingZero =
            derSet[2] === 0x02 && derSet[3] === 0x21 && derSet[4] === 0x00;

        record('Test 6: DER round-trip (high-bit clear and set) + leading-0x00 pad',
            clearRoundTrip && setRoundTrip && setEncodingHasLeadingZero,
            `clear=${clearRoundTrip} set=${setRoundTrip} leadingZero=${setEncodingHasLeadingZero}`);
    }

    // ── Test 7: invalid public key (not on curve) is rejected ───────────
    {
        const fakePublicKey = { x: 1n, y: 1n };       // (1,1) is not on P-256
        // Sanity: confirm our isOnCurve agrees the point is invalid
        const offCurveConfirmed = !isOnCurve(fakePublicKey);
        // verifyECDSA must reject regardless of how plausible the sig looks
        const rejected = !verifyECDSA('hello world', validSig, fakePublicKey);
        record('Test 7: verify rejects public key not on the curve',
            offCurveConfirmed && rejected,
            `offCurveConfirmed=${offCurveConfirmed} rejected=${rejected}`);
    }

    process.exit(allPass ? 0 : 1);
}
